### ISSUE TITLE
No syntax highlighting?

### ISSUE THREAD

**Issue by lnicola** [iwillspeak/docket#11]
I can't get the syntax highlighting to work:

![image](https://user-images.githubusercontent.com/308347/56454409-b49d7280-6358-11e9-9f23-3b017752bac5.png)

I did open the docs from an HTTP server, not from disk:

![image](https://user-images.githubusercontent.com/308347/56454412-cbdc6000-6358-11e9-9821-453b9b5001c3.png)

![image](https://user-images.githubusercontent.com/308347/56454415-d5fe5e80-6358-11e9-8f7e-ed5a361947bb.png)

**Comment by lnicola** [comment]
Never mind, I'm stupid :smile:.

**Comment by iwillspeak** [comment]
Just to confirm here the docs you linked to are supposed to show the Markdown source code that would result in highlighted text. They aren't supposed to be highlighted themselves.

**Comment by lnicola** [comment]
I realized once I looked at the source. You might want to add a highlighted snippet just to show what it looks like.

**Comment by iwillspeak** [comment]
That's a good idea. I'll create a new issue to track that.
